[project]
name = "dj-bucket"
version = "0.1.0"
authors = [{ name = "Benjamin Hirschfield", email = "me@bennybarry.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
]
description = "Use your database as a S3 storage"
license = { text = "MIT" }
requires-python = ">=3.11,<4"
readme = "README.md"

dependencies = [
    "django >=4.1,<6.0",
]

[dependency-groups]
dev = [
    "mypy >=2.3.1,<3",
    "pytest >=9.1.1,<10",
    "pytest-cov >=7.1.0,<8",
    "pytest-django >=4.14.0,<5",
    "ruff >=0.15.18,<1",
]

[tool.pyright]
typeCheckingMode = "basic"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 88
target-version = "py312"
extend-exclude = ["dj_bucket/migrations"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"

[tool.mypy]
ignore_missing_imports = true
exclude = 'migrations/'

[[tool.mypy.overrides]]
module = "dj_bucket.*"
disallow_any_generics = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "django.*",
  "wagtail.*",
]
ignore_missing_imports = true
