# Generated by Django 4.2.29 on 2026-04-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BucketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw", models.BinaryField()),
                ("path", models.CharField(max_length=255, unique=True)),
                ("mimetype", models.CharField(max_length=64)),
                ("accessed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
            ],
        ),
    ]
