# Generated by Django 5.2.17 on 2026-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_bucket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketitem',
            name='raw',
            field=models.BinaryField(),
        ),
    ]
